Подключил в проект checkstyle
Cerlace/JD2_Group_Works pull request #14
Opened 2024-11-30 20:58 UTC by romangulyako

Настроил checkstyle для проверки кода, пока закомментировал правила для проверки на наличие и корректность Javadoc

2024-11-30 22:38 UTC, Cerlace requested changes
Отпиши если у тебя нет такой проблемы, просто я ее обнаружил еще когда Jacoco ставил

2024-11-30 22:38 UTC, Cerlace commented on Group_Work_2_DAO_Hibernate/pom.xml
>            <artifactId>maven-clean-plugin</artifactId>
Убери в этой секции тег <pluginManagement>, или же сделай после нее еще одну секцию <plugins> и в нее вставь плагин, иначе мавен не видит его

2024-12-01 07:24 UTC, romangulyako commented on Group_Work_2_DAO_Hibernate/pom.xml
>            <artifactId>maven-clean-plugin</artifactId>
Понял о чем ты, не заметил сразу. Сделал. Лишнее вообще убрал

2024-12-01 10:35 UTC, Cerlace approved these changes

2024-12-01 10:35 UTC, merged