Добавил логирование для DAO и заменил печать в консоль
Cerlace/JD2_Group_Works pull request #29
Opened 2024-12-08 09:32 UTC by romangulyako

Для DAO сделал логирование только в файл, а для команд и принтеров просто заменил System.out.println на печать в консоль логов. Насколько я понял, Гена это имел ввиду, хз) Если это не нужно будет, то просто можно откатить коммит и оставить только для DAO. По сути как само логирование, то только для DAO оно и нужно. А то, что для приложения заменил это уже просто еще один способ вывода в печать.

2024-12-08 13:23 UTC, Cerlace requested changes
Там еще можно подумать над уровнем сообщений для ошибок (некоторые на WARN поменять, но это уже не так важно)

2024-12-08 13:23 UTC, Cerlace commented on Group_Work_2_DAO_Hibernate/pom.xml
>      </dependencies>
Последняя депенденси уже включает первые две, так что по сути они лишние

2024-12-08 13:23 UTC, Cerlace commented on Group_Work_2_DAO_Hibernate/src/main/java/itacademy/commands/DeleteCommand.java
> +            this.logger.debug(ROW_NOT_FOUND, id);
Думаю лучше этим сообщениям уровень INFO. И в остальных командах соответственно тоже

2024-12-08 13:23 UTC, Cerlace commented on Group_Work_2_DAO_Hibernate/src/main/java/itacademy/utils/ExecutorUtils.java
>              return t;
А вот это наоборот уровня DEBUG. Идея в том, что INFO сообщения нам могут быть нужны в работе приложения (как из команд например), а DEBUG только при отладке (ну типо зачем нам в обычной ситуации знать что там с транзакцией произошло, только если будем дебажить это уже интересно)

2024-12-08 15:47 UTC, romangulyako commented on Group_Work_2_DAO_Hibernate/src/main/java/itacademy/commands/DeleteCommand.java
> +            this.logger.debug(ROW_NOT_FOUND, id);
Ну они по сути тут используются просто вместо систем аут, поэтому сильной разницы нет, но вообще может и можно

2024-12-08 15:50 UTC, romangulyako commented on Group_Work_2_DAO_Hibernate/src/main/java/itacademy/utils/ExecutorUtils.java
>              return t;
Ну смотри, я наоборот читал, что такое должно быть в инфо, чтобы мы потом могли видеть, в проде, что например обновлялась строка с id таким-то и транзакция завершена успешно или ошибка. Потому что дебаг в проде отключается как правило и как нам узнать какие операции с бд проводились и когда?
Sql скрипты от гибернейта уровня дебаг + там просто запрос с вопросиками. А так у нас в логах будет информация о совершенных транзакциях

2024-12-09 11:55 UTC, Cerlace approved these changes

2024-12-09 11:55 UTC, merged