Поправил каскадные типы и добавил DAO
Cerlace/JD2_Group_Works pull request #35
Opened 2024-12-15 19:52 UTC by romangulyako

Где-то костыльно, где-то не все предусмотрел, но пока как есть. Переделал каскады, чтобы объекты были и независимы где надо, и работали в связке где надо. В DAO за основу взял с прошлой домашки, но тоже не очень много времени было, что смог. Для отдельных дао классов придумал доп. метод только для студентов и оценок. Возможно есть еще идеи. + не написал документацию и в мэйне много магических чисел. Это по чекстайлу

2024-12-16 15:06 UTC, Cerlace commented on Group_Work_3_Courses/src/main/java/itacademy/entity/Task.java
> +            mappedBy = "task")
А тут добавить CascadeType.MERGE - чтобы можно было обновить и добавить/удалить оценок. И CascadeType.PERSIST можно, но не уверен правильно ли добавлять новую оценку через новую задачу

2024-12-16 15:14 UTC, Cerlace requested changes
Как минимум persist ы добавить было бы хорошо

2024-12-16 15:23 UTC, romangulyako commented on Group_Work_3_Courses/src/main/java/itacademy/dao/impl/GradeDAOImpl.java
> +            }
Да, действительно, переделаю

2024-12-16 15:26 UTC, romangulyako commented on Group_Work_3_Courses/src/main/java/itacademy/dao/impl/StudentDAOImpl.java
> +}
Не совсем понял

2024-12-16 15:28 UTC, romangulyako commented on Group_Work_3_Courses/src/main/java/itacademy/entity/Course.java
Ну я уже к этому тоже пришел. Вначале хотел максимально независимыми их сделать

2024-12-16 15:30 UTC, romangulyako commented on Group_Work_3_Courses/src/main/java/itacademy/entity/Task.java
> +            mappedBy = "task")
Я тут подумал, что изменять и добавлять оценки нужно через студента, а не таску. Только удалять если удаляем задание

2024-12-16 15:32 UTC, romangulyako commented on Group_Work_3_Courses/src/main/java/itacademy/entity/Teacher.java
> +            mappedBy = "teacher")
Опять же, не добавлял, чтобы не было такой сильной зависимости
Но хз, может и нужно

2024-12-16 15:57 UTC, Cerlace commented on Group_Work_3_Courses/src/main/java/itacademy/dao/impl/StudentDAOImpl.java
> +}
Сделать createQuery, а потом setParameter – как в другом методе. А у тебя просто конкатенация строк

2024-12-16 15:58 UTC, Cerlace commented on Group_Work_3_Courses/src/main/java/itacademy/entity/Task.java
> +            mappedBy = "task")
А, ну в принципе логично

2024-12-16 16:10 UTC, Cerlace commented on Group_Work_3_Courses/src/main/java/itacademy/entity/Teacher.java
> +            mappedBy = "teacher")
Да оно никакой зависимости в принципе не добавляет, просто за нас делает persist

2024-12-16 16:57 UTC, romangulyako commented on Group_Work_3_Courses/src/main/java/itacademy/dao/impl/StudentDAOImpl.java
> +}
Се, понял. Да, изменю

2024-12-17 14:58 UTC, Cerlace approved these changes

2024-12-17 14:59 UTC, merged