Классы entity, DAO, утилитные классы
Cerlace/JD2_Group_Works pull request #44
Opened 2024-12-22 19:20 UTC by Simon35845

Написал CarEntity
Добавил ExecutorUtil, HibernateExecutor, ReflectionUtil
Написал DAOImpl, CarDAOImpl

2024-12-22 19:54 UTC, Cerlace requested changes

2024-12-22 19:54 UTC, Cerlace commented on Group_Work_4_CarServlet/src/main/java/itacademy/entity/CarEntity.java
> +public class CarEntity implements Serializable {
добавь к table параметр name = "cars" - иначе таблица будет называться CarEntiy

2024-12-22 20:29 UTC, romangulyako requested changes
Вообще как по мне не обязательно делать DaoImpl, а потом расширять до CarDaoImpl. В предыдущих домашках мы так делали, потому что задача была такая, чтобы был универсальный дао, а теперь задача по работе с конкретной таблицей, поэтому это избыточно. Можно напрямую имплементить. Но это не критично

2024-12-22 20:29 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/dao/impl/CarDAOImpl.java
> +    private final EntityManager em;
Это поле здесь не нужно

2024-12-22 20:29 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/dao/impl/DAOImpl.java
> +        this.tableName = ReflectionUtil.getTableNameByClass(clazz);
Здесь тоже можно избавиться от рефлексии и в логи писать имя entity, о чем Гена говорил, чтобы рефлексией не тормозить приложение, соответственно и поле tableName убрать

2024-12-22 20:29 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/dao/impl/DAOImpl.java
> +    protected EntityManager getEntityManager() {
Этот метод для нашей задачи тоже не нужен

2024-12-22 20:29 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/dao/impl/DAOImpl.java
> +    public T get(Serializable id) {
И этот не нужен

2024-12-22 20:29 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/dao/impl/DAOImpl.java
> +        String query = "FROM " + this.tableName;
Здесь если уберем рефлексию, то нужно переписать запрос на jpql

2024-12-22 20:29 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/dao/impl/DAOImpl.java
> +        String query = "FROM " + this.tableName;
Здесь если уберем рефлексию, то нужно переписать запрос на jpql

2024-12-22 20:29 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/dao/impl/DAOImpl.java
> +        ReflectionUtil.setId(t, id);
Это можно убрать, просто в метод засовывать entity уже с айдишником  и тогда вообще избавимся от класса ReflectionUtils

2024-12-22 20:29 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/entity/CarEntity.java
> +}
Как вариант для наглядности можно какое-нибудь поле еще добавить, чтобы dto и entity отличались. Например время изменения или что-то такое. Но вообще это не обязательно

2024-12-23 08:48 UTC, romangulyako requested changes

2024-12-23 08:48 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/dao/impl/DAOImpl.java
> +    public T update(Serializable id, T t) throws IllegalAccessException {
здесь еще можно убрать throws IllegalAccessExeption. Нам этот проброс здесь не нужен, если уберем ReflectionUtil.setId. И в интерфейск DAO нужно будет убрать. Чтобы не делать дополнительных try/catch потом

2024-12-23 18:56 UTC, Cerlace approved these changes

2024-12-23 18:58 UTC, Cerlace commented on Group_Work_4_CarServlet/src/main/java/itacademy/dao/DAO.java
Незачем оставлять закомментированным - удали просто

2024-12-23 20:03 UTC, Cerlace approved these changes

2024-12-23 20:08 UTC, merged