sergey_part
Cerlace/JD2_Group_Works pull request #45
Opened 2024-12-22 23:36 UTC by SergeyIvantsov

Создал таблицу в схеме group_hw_4 ,  с классом liquiRunner,  log подключил, но опробовал только на одном классе.

2024-12-23 06:02 UTC, romangulyako requested changes
Ситуация как у Саймона, в PR не должно быть изменений из предыдущих домашек

2024-12-23 06:02 UTC, romangulyako commented on Group_Work_4_CarServlet/pom.xml
> +<!--                <artifactId>maven-checkstyle-plugin</artifactId>-->
А для чего закомментировал checkstyle?

2024-12-23 06:02 UTC, romangulyako commented on Group_Work_4_CarServlet/for_tests/resources/log4j2.xml
Все что для тестов закинь в src/test, а не в for_tests

2024-12-23 15:49 UTC, SergeyIvantsov commented on Group_Work_4_CarServlet/src/main/java/itacademy/LiquiRunner.java
> +public class LiquiRunner {
Я его использовал для запуска таблицы БД. Просто если его не будет, как понять, что таблицы появились? С чего запускать?

2024-12-23 15:51 UTC, SergeyIvantsov commented on Group_Work_4_CarServlet/pom.xml
> +<!--                <artifactId>maven-checkstyle-plugin</artifactId>-->
Checkstyle в некоторых местах при запуске ругался, что нету описания проекта в самом коде, поэтому пришлось на время закомментить

2024-12-23 16:03 UTC, romangulyako commented on Group_Work_4_CarServlet/pom.xml
> +<!--                <artifactId>maven-checkstyle-plugin</artifactId>-->
Такие файлы лучше не коммитить тогда, которые для работы правишь временно, потом можем забыть вернуть обратно и получится на финише на закомментированный плагин

2024-12-23 19:59 UTC, Cerlace commented on Group_Work_4_CarServlet/src/main/resources/db/changelog/V1.0.0-create-tables/2024-12-21-create-carEntity-table.xml
> +            <column name="id" type="bigint" autoIncrement="true">
bigint в SQL это Long в Java - поменяй на int

2024-12-24 06:24 UTC, romangulyako requested changes

2024-12-24 06:24 UTC, romangulyako commented on Group_Work_4_CarServlet/src/main/java/itacademy/entity/Car.java
> +public class Car implements Serializable {
Entity класс вообще уже есть, но его в любом случае нужно назвать CarEntity, т.к. дальше везде в приложении используется это название класса

2024-12-24 12:51 UTC, closed without merging